sonar.sources=src/conekta_mcp
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage/coverage.xml
sonar.python.xunit.reportPath=coverage/report.xml
sonar.sourceEncoding=UTF-8
sonar.projectKey=conekta_mcp-server_8b7e4783-b0f9-4160-923f-51e6e5f0876a
