service_name: mcp-server
type: ssr
internal: true
subdomain: mcp
container_port: 8000
container_cpu: 256
container_memory: 512
service_desired_count: 1
healthcheck_path: /ping
dockerfile: Dockerfile
metadata:
  team: core
  source: python
environment:
  - name: "ENV"
    value: "stg"
  - name: "PORT"
    value: "8000"
  - name: "CONEKTA_MCP_HOST"
    value: "0.0.0.0"
  - name: "CONEKTA_MCP_PORT"
    value: "8000"
  - name: "CONEKTA_MCP_STREAMABLE_HTTP_PATH"
    value: "/mcp"
  - name: "CONEKTA_MCP_TRANSPORT"
    value: "streamable-http"
